/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment/callback'
import { Route as StoreVendorSlugRouteImport } from './routes/store/$vendorSlug'
import { Route as ApiCronEmailRouteImport } from './routes/api/cron/email'
import { Route as ApiWebhooksFlutterwaveRouteImport } from './routes/api/webhooks/flutterwave'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as StoreVendorSlugProductProductSlugRouteImport } from './routes/store/$vendorSlug/product/$productSlug'
import { Route as StoreVendorSlugFeedsCatalogXmlRouteImport } from './routes/store/$vendorSlug/feeds/catalog.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreVendorSlugRoute = StoreVendorSlugRouteImport.update({
  id: '/store/$vendorSlug',
  path: '/store/$vendorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmailRoute = ApiCronEmailRouteImport.update({
  id: '/api/cron/email',
  path: '/api/cron/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksFlutterwaveRoute = ApiWebhooksFlutterwaveRouteImport.update({
  id: '/api/webhooks/flutterwave',
  path: '/api/webhooks/flutterwave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreVendorSlugProductProductSlugRoute =
  StoreVendorSlugProductProductSlugRouteImport.update({
    id: '/product/$productSlug',
    path: '/product/$productSlug',
    getParentRoute: () => StoreVendorSlugRoute,
  } as any)
const StoreVendorSlugFeedsCatalogXmlRoute =
  StoreVendorSlugFeedsCatalogXmlRouteImport.update({
    id: '/feeds/catalog/xml',
    path: '/feeds/catalog/xml',
    getParentRoute: () => StoreVendorSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-call': typeof BookCallRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/store/$vendorSlug': typeof StoreVendorSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cron/email': typeof ApiCronEmailRoute
  '/api/webhooks/flutterwave': typeof ApiWebhooksFlutterwaveRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/store/$vendorSlug/product/$productSlug': typeof StoreVendorSlugProductProductSlugRoute
  '/store/$vendorSlug/feeds/catalog/xml': typeof StoreVendorSlugFeedsCatalogXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-call': typeof BookCallRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/store/$vendorSlug': typeof StoreVendorSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/cron/email': typeof ApiCronEmailRoute
  '/api/webhooks/flutterwave': typeof ApiWebhooksFlutterwaveRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/store/$vendorSlug/product/$productSlug': typeof StoreVendorSlugProductProductSlugRoute
  '/store/$vendorSlug/feeds/catalog/xml': typeof StoreVendorSlugFeedsCatalogXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-call': typeof BookCallRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/store/$vendorSlug': typeof StoreVendorSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/cron/email': typeof ApiCronEmailRoute
  '/api/webhooks/flutterwave': typeof ApiWebhooksFlutterwaveRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/store/$vendorSlug/product/$productSlug': typeof StoreVendorSlugProductProductSlugRoute
  '/store/$vendorSlug/feeds/catalog/xml': typeof StoreVendorSlugFeedsCatalogXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-call'
    | '/catalog'
    | '/contact'
    | '/cookies'
    | '/features'
    | '/help'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/track'
    | '/payment/callback'
    | '/store/$vendorSlug'
    | '/admin/'
    | '/dashboard/'
    | '/api/cron/email'
    | '/api/webhooks/flutterwave'
    | '/api/webhooks/paystack'
    | '/store/$vendorSlug/product/$productSlug'
    | '/store/$vendorSlug/feeds/catalog/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-call'
    | '/catalog'
    | '/contact'
    | '/cookies'
    | '/features'
    | '/help'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/track'
    | '/payment/callback'
    | '/store/$vendorSlug'
    | '/admin'
    | '/dashboard'
    | '/api/cron/email'
    | '/api/webhooks/flutterwave'
    | '/api/webhooks/paystack'
    | '/store/$vendorSlug/product/$productSlug'
    | '/store/$vendorSlug/feeds/catalog/xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-call'
    | '/catalog'
    | '/contact'
    | '/cookies'
    | '/features'
    | '/help'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/track'
    | '/payment/callback'
    | '/store/$vendorSlug'
    | '/admin/'
    | '/dashboard/'
    | '/api/cron/email'
    | '/api/webhooks/flutterwave'
    | '/api/webhooks/paystack'
    | '/store/$vendorSlug/product/$productSlug'
    | '/store/$vendorSlug/feeds/catalog/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookCallRoute: typeof BookCallRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FeaturesRoute: typeof FeaturesRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  StoreVendorSlugRoute: typeof StoreVendorSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiCronEmailRoute: typeof ApiCronEmailRoute
  ApiWebhooksFlutterwaveRoute: typeof ApiWebhooksFlutterwaveRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$vendorSlug': {
      id: '/store/$vendorSlug'
      path: '/store/$vendorSlug'
      fullPath: '/store/$vendorSlug'
      preLoaderRoute: typeof StoreVendorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/email': {
      id: '/api/cron/email'
      path: '/api/cron/email'
      fullPath: '/api/cron/email'
      preLoaderRoute: typeof ApiCronEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/flutterwave': {
      id: '/api/webhooks/flutterwave'
      path: '/api/webhooks/flutterwave'
      fullPath: '/api/webhooks/flutterwave'
      preLoaderRoute: typeof ApiWebhooksFlutterwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$vendorSlug/product/$productSlug': {
      id: '/store/$vendorSlug/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/store/$vendorSlug/product/$productSlug'
      preLoaderRoute: typeof StoreVendorSlugProductProductSlugRouteImport
      parentRoute: typeof StoreVendorSlugRoute
    }
    '/store/$vendorSlug/feeds/catalog/xml': {
      id: '/store/$vendorSlug/feeds/catalog/xml'
      path: '/feeds/catalog/xml'
      fullPath: '/store/$vendorSlug/feeds/catalog/xml'
      preLoaderRoute: typeof StoreVendorSlugFeedsCatalogXmlRouteImport
      parentRoute: typeof StoreVendorSlugRoute
    }
  }
}

interface StoreVendorSlugRouteChildren {
  StoreVendorSlugProductProductSlugRoute: typeof StoreVendorSlugProductProductSlugRoute
  StoreVendorSlugFeedsCatalogXmlRoute: typeof StoreVendorSlugFeedsCatalogXmlRoute
}

const StoreVendorSlugRouteChildren: StoreVendorSlugRouteChildren = {
  StoreVendorSlugProductProductSlugRoute:
    StoreVendorSlugProductProductSlugRoute,
  StoreVendorSlugFeedsCatalogXmlRoute: StoreVendorSlugFeedsCatalogXmlRoute,
}

const StoreVendorSlugRouteWithChildren = StoreVendorSlugRoute._addFileChildren(
  StoreVendorSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookCallRoute: BookCallRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FeaturesRoute: FeaturesRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  StoreVendorSlugRoute: StoreVendorSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiCronEmailRoute: ApiCronEmailRoute,
  ApiWebhooksFlutterwaveRoute: ApiWebhooksFlutterwaveRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
